/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;
import model.bean.BudgetsDetails;
import model.dao.BudgetsDAO;
import model.dao.BudgetsDetailsDAO;
import model.dao.ProductsDAO;
import model.bean.Budgets;
import model.bean.Products;

/**
 *
 * @author Tong
 */
public class FBudgetsDetails extends javax.swing.JFrame {

    /**
     * Creates new form FBudgetsDetails
     */
    public FBudgetsDetails() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTBudgetDetails.getModel();
        jTBudgetDetails.setRowSorter(new TableRowSorter(modelo));

        readJTable();
        BudgetsDAO bDAO = new BudgetsDAO();
        ProductsDAO prdao = new ProductsDAO();
        for (Products pr : prdao.list()) {
            listProducts.setSelectedItem(null);
            listProducts.addItem(pr);
        }
        for (Budgets bu : bDAO.list()) {
            listBudgets.setSelectedItem(null);
            listBudgets.addItem(bu);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTBudgetDetails = new javax.swing.JTable();
        txtIdBudgetDetails = new javax.swing.JTextField();
        txtSubtotalBudgetDetails = new javax.swing.JTextField();
        txtQtBudgetDetails = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPrecoBudgetDetails = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtBuscaBudgetDetails = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        listProducts = new javax.swing.JComboBox<>();
        listBudgets = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTBudgetDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PREÇO", "QUANTIDADE", "SUBTOTAL", "PRODUTO", "ORÇAMENTO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTBudgetDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTBudgetDetailsMouseClicked(evt);
            }
        });
        jTBudgetDetails.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTBudgetDetailsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTBudgetDetails);
        if (jTBudgetDetails.getColumnModel().getColumnCount() > 0) {
            jTBudgetDetails.getColumnModel().getColumn(5).setMaxWidth(200);
        }

        txtIdBudgetDetails.setEnabled(false);

        jLabel6.setText("QUANTIDADE");

        jLabel2.setText("PREÇO");

        jLabel4.setText("SUBTOTAL");

        jLabel11.setText("PRODUTO");

        jLabel9.setText("ID");

        jLabel12.setText("ORÇAMENTO");

        jButton4.setText("Busca");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtBuscaBudgetDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaBudgetDetailsActionPerformed(evt);
            }
        });

        jButton3.setText("Atualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(135, 135, 135))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4)
                                        .addComponent(txtSubtotalBudgetDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                                    .addComponent(txtIdBudgetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtQtBudgetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listProducts, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel12))
                                .addGap(0, 227, Short.MAX_VALUE))
                            .addComponent(txtPrecoBudgetDetails)
                            .addComponent(listBudgets, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscaBudgetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(30, 30, 30)
                        .addComponent(jButton2)
                        .addGap(26, 26, 26)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscaBudgetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(txtSubtotalBudgetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQtBudgetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdBudgetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecoBudgetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listBudgets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void readJTable() {

        DefaultTableModel modelo = (DefaultTableModel) jTBudgetDetails.getModel();
        modelo.setNumRows(0);
        BudgetsDetailsDAO pdao = new BudgetsDetailsDAO();
        BudgetsDAO bDAO = new BudgetsDAO();
        ProductsDAO prdao = new ProductsDAO();
        for (BudgetsDetails p : pdao.list()) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getPrice(),
                p.getAmount(),
                p.getSubtotal(),
                p.getProduct(),
                p.getBudget()
            });

        }

    }

    public void readJTableForDesc(String nameProduct) {

        DefaultTableModel modelo = (DefaultTableModel) jTBudgetDetails.getModel();
        modelo.setNumRows(0);
        BudgetsDetailsDAO pdao = new BudgetsDetailsDAO();
        BudgetsDAO bDAO = new BudgetsDAO();
        ProductsDAO prdao = new ProductsDAO();
        for (BudgetsDetails p : pdao.loadByProduct(nameProduct)) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getPrice(),
                p.getAmount(),
                p.getSubtotal(),
                p.getProduct(),
                p.getBudget()
            });

        }

    }

    private void jTBudgetDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBudgetDetailsMouseClicked
        if (jTBudgetDetails.getSelectedRow() != -1) {

            txtIdBudgetDetails.setText(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 0).toString());
            txtPrecoBudgetDetails.setText(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 1).toString());
            txtQtBudgetDetails.setText(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 2).toString());
            txtSubtotalBudgetDetails.setText(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 3).toString());
            listProducts.setSelectedItem(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 4));
            listBudgets.setSelectedItem(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 5));

        }
    }//GEN-LAST:event_jTBudgetDetailsMouseClicked

    private void jTBudgetDetailsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBudgetDetailsKeyReleased
        if (jTBudgetDetails.getSelectedRow() != -1) {

            txtIdBudgetDetails.setText(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 0).toString());
            txtPrecoBudgetDetails.setText(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 1).toString());
            txtQtBudgetDetails.setText(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 2).toString());
            txtSubtotalBudgetDetails.setText(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 3).toString());
            listProducts.setSelectedItem(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 4));
            listBudgets.setSelectedItem(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 5));
        }
    }//GEN-LAST:event_jTBudgetDetailsKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        readJTableForDesc(txtBuscaBudgetDetails.getText());

    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtBuscaBudgetDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaBudgetDetailsActionPerformed
        jButton4.setEnabled(true);
    }//GEN-LAST:event_txtBuscaBudgetDetailsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jTBudgetDetails.getSelectedRow() != -1) {

            try {

                BudgetsDetails p = new BudgetsDetails();
                BudgetsDetailsDAO dao = new BudgetsDetailsDAO();
                Products products = (Products) listProducts.getSelectedItem();
                Budgets budgets = (Budgets) listBudgets.getSelectedItem();
                p.setPrice(Double.parseDouble(txtPrecoBudgetDetails.getText()));
                p.setAmount(Integer.parseInt(txtQtBudgetDetails.getText()));
                p.setSubtotal(Double.parseDouble(txtSubtotalBudgetDetails.getText()));
                p.setBudget(budgets);
                p.setProduct(products);
                p.setId((int) jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 0));

                dao.alter(p);

                txtIdBudgetDetails.setText("");
                txtPrecoBudgetDetails.setText("");
                txtQtBudgetDetails.setText("");
                txtSubtotalBudgetDetails.setText("");

                readJTable();

            } catch (Exception ex) {
                Logger.getLogger(FBudgetsDetails.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTBudgetDetails.getSelectedRow() != -1) {

            try {

                BudgetsDetails p = new BudgetsDetails();
                BudgetsDetailsDAO dao = new BudgetsDetailsDAO();

                p.setId((int) jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 0));

                dao.delete(p);

                txtIdBudgetDetails.setText("");
                txtPrecoBudgetDetails.setText("");
                txtQtBudgetDetails.setText("");
                txtSubtotalBudgetDetails.setText("");

                readJTable();

            } catch (Exception ex) {
                Logger.getLogger(FBudgetsDetails.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um budget para excluir.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            BudgetsDetails p = new BudgetsDetails();
            BudgetsDetailsDAO dao = new BudgetsDetailsDAO();
            Products products = (Products) listProducts.getSelectedItem();
            Budgets budgets = (Budgets) listBudgets.getSelectedItem();
            p.setPrice(Double.parseDouble(txtPrecoBudgetDetails.getText()));
            p.setAmount(Integer.parseInt(txtQtBudgetDetails.getText()));
            p.setSubtotal(Double.parseDouble(txtSubtotalBudgetDetails.getText()));
            p.setBudget(budgets);
            p.setProduct(products);
            dao.create(p);
            txtIdBudgetDetails.setText("");
            txtPrecoBudgetDetails.setText("");
            txtQtBudgetDetails.setText("");
            txtSubtotalBudgetDetails.setText("");
            readJTable();

        } catch (Exception ex) {
            Logger.getLogger(FBudget.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FBudgetsDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FBudgetsDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FBudgetsDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FBudgetsDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FBudgetsDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBudgetDetails;
    private javax.swing.JComboBox<Object> listBudgets;
    private javax.swing.JComboBox<Object> listProducts;
    private javax.swing.JTextField txtBuscaBudgetDetails;
    private javax.swing.JTextField txtIdBudgetDetails;
    private javax.swing.JTextField txtPrecoBudgetDetails;
    private javax.swing.JTextField txtQtBudgetDetails;
    private javax.swing.JTextField txtSubtotalBudgetDetails;
    // End of variables declaration//GEN-END:variables
}
