/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.bean.Budgets;
import model.dao.BudgetsDAO;

/**
 *
 * @author Tong
 */
public class FBudget extends javax.swing.JFrame {

    /**
     * Creates new form Budget
     */
    public FBudget() {
        initComponents();
        
        jButton4.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtQuantBudget = new javax.swing.JTextField();
        txtPrecoBudget = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSubtotalBudget = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtDescricaoBudget = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBudgtcolBudget = new javax.swing.JTextField();
        txtIdBudget = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBudget = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtBuscaBudget = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel9.setText("ID");

        jLabel11.setText("BUDGTCOL");

        jLabel4.setText("SUBTOTAL");

        jLabel2.setText("PREÇO");

        jLabel1.setText("DESCRIÇÃO");

        jLabel5.setText("QUANTIDADE");

        jTBudget.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PREÇO", "QUANTIDADE", "SUBTOTAL", "BUDGCOL", "DESCRIÇÃO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTBudget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTBudgetMouseClicked(evt);
            }
        });
        jTBudget.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTBudgetKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTBudget);
        if (jTBudget.getColumnModel().getColumnCount() > 0) {
            jTBudget.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Atualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtBuscaBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaBudgetActionPerformed(evt);
            }
        });

        jButton4.setText("Busca");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(txtQuantBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtPrecoBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(txtDescricaoBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(txtSubtotalBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(133, 133, 133)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(txtBudgtcolBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(30, 30, 30)
                        .addComponent(jButton2)
                        .addGap(26, 26, 26)
                        .addComponent(jButton3)
                        .addGap(163, 163, 163)
                        .addComponent(txtBuscaBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuantBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecoBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSubtotalBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBudgtcolBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDescricaoBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscaBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton3)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void readJTable() throws SQLException {
        
        DefaultTableModel modelo = (DefaultTableModel) jTBudget.getModel();
        modelo.setNumRows(0);
        BudgetsDAO pdao = new BudgetsDAO();

        for (Budgets p : pdao.read()) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getPrice(),
                p.getAmount(),
                p.getSubtotal(),
                p.getBudgcol(),
                p.getDescription()
            });

        }

    }
    
    
    public void readJTableForDesc(String desc) throws SQLException {
        
        DefaultTableModel modelo = (DefaultTableModel) jTBudget.getModel();
        modelo.setNumRows(0);
        BudgetsDAO pdao = new BudgetsDAO();

        for (Budgets p : pdao.readForDesc(desc)) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getPrice(),
                p.getAmount(),
                p.getSubtotal(),
                p.getBudgcol(),
                p.getDescription()
            });

        }

    }
    private void jTBudgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBudgetMouseClicked
        if (jTBudget.getSelectedRow() != -1) {

            txtIdBudget.setText(jTBudget.getValueAt(jTBudget.getSelectedRow(), 1).toString());
            txtPrecoBudget.setText(jTBudget.getValueAt(jTBudget.getSelectedRow(), 2).toString());
            txtQuantBudget.setText(jTBudget.getValueAt(jTBudget.getSelectedRow(), 3).toString());
            txtSubtotalBudget.setText(jTBudget.getValueAt(jTBudget.getSelectedRow(), 4).toString());
            txtBudgtcolBudget.setText(jTBudget.getValueAt(jTBudget.getSelectedRow(), 5).toString());
            txtDescricaoBudget.setText(jTBudget.getValueAt(jTBudget.getSelectedRow(), 6).toString());
            
        }
    }//GEN-LAST:event_jTBudgetMouseClicked

    private void jTBudgetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBudgetKeyReleased
        if (jTBudget.getSelectedRow() != -1) {

            txtIdBudget.setText(jTBudget.getValueAt(jTBudget.getSelectedRow(), 1).toString());
            txtPrecoBudget.setText(jTBudget.getValueAt(jTBudget.getSelectedRow(), 2).toString());
            txtQuantBudget.setText(jTBudget.getValueAt(jTBudget.getSelectedRow(), 3).toString());
            txtSubtotalBudget.setText(jTBudget.getValueAt(jTBudget.getSelectedRow(), 4).toString());
            txtBudgtcolBudget.setText(jTBudget.getValueAt(jTBudget.getSelectedRow(), 5).toString());
            txtDescricaoBudget.setText(jTBudget.getValueAt(jTBudget.getSelectedRow(), 6).toString());
        }
    }//GEN-LAST:event_jTBudgetKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Budgets p = new Budgets();
            BudgetsDAO dao = new BudgetsDAO();

            p.setId(Integer.parseInt(txtIdBudget.getText()));
            p.setPrice(Integer.parseInt(txtPrecoBudget.getText()));
            p.setAmount(Integer.parseInt(txtQuantBudget.getText()));
            p.setSubtotal(Double.parseDouble(txtSubtotalBudget.getText()));
            p.setBudgcol(Double.parseDouble(txtBudgtcolBudget.getText()));
            p.setDescription(txtDescricaoBudget.getText());
            dao.create(p);

            txtIdBudget.setText("");
            txtPrecoBudget.setText("");
            txtQuantBudget.setText("");
            txtSubtotalBudget.setText("");
            txtBudgtcolBudget.setText("");
            txtDescricaoBudget.setText("");

            readJTable();

        } catch (SQLException ex) {
            Logger.getLogger(FBudget.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FBudget.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTBudget.getSelectedRow() != -1) {

            try {

                Budgets p = new Budgets();
                BudgetsDAO dao = new BudgetsDAO();

                p.setId((int) jTBudget.getValueAt(jTBudget.getSelectedRow(), 0));

                dao.delete(p);

                txtIdBudget.setText("");
                txtPrecoBudget.setText("");
                txtQuantBudget.setText("");
                txtSubtotalBudget.setText("");
                txtBudgtcolBudget.setText("");
                txtDescricaoBudget.setText("");


                readJTable();

            } catch (SQLException ex) {
                Logger.getLogger(FBudget.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente para excluir.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jTBudget.getSelectedRow() != -1) {

            try {

                Budgets p = new Budgets();
                BudgetsDAO dao = new BudgetsDAO();

                p.setId(Integer.parseInt(txtIdBudget.getText()));
                p.setPrice(Integer.parseInt(txtPrecoBudget.getText()));
                p.setAmount(Integer.parseInt(txtQuantBudget.getText()));
                p.setSubtotal(Double.parseDouble(txtSubtotalBudget.getText()));
                p.setBudgcol(Double.parseDouble(txtBudgtcolBudget.getText()));
                p.setDescription(txtDescricaoBudget.getText());
                p.setId((int) jTBudget.getValueAt(jTBudget.getSelectedRow(), 0));

                try {
                    dao.update(p);
                } catch (SQLException ex) {
                    Logger.getLogger(FBudget.class.getName()).log(Level.SEVERE, null, ex);
                }

                txtIdBudget.setText("");
                txtPrecoBudget.setText("");
                txtQuantBudget.setText("");
                txtSubtotalBudget.setText("");
                txtBudgtcolBudget.setText("");
                txtDescricaoBudget.setText("");
                readJTable();

            } catch (SQLException ex) {
                Logger.getLogger(FBudget.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtBuscaBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaBudgetActionPerformed
        jButton4.setEnabled(true);
    }//GEN-LAST:event_txtBuscaBudgetActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            readJTableForDesc(txtBuscaBudget.getText());
        } catch (SQLException ex) {
            Logger.getLogger(FBudget.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FBudget().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBudget;
    private javax.swing.JTextField txtBudgtcolBudget;
    private javax.swing.JTextField txtBuscaBudget;
    private javax.swing.JTextField txtDescricaoBudget;
    private javax.swing.JTextField txtIdBudget;
    private javax.swing.JTextField txtPrecoBudget;
    private javax.swing.JTextField txtQuantBudget;
    private javax.swing.JTextField txtSubtotalBudget;
    // End of variables declaration//GEN-END:variables
}
