/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.image.BufferedImage;
import java.io.File;
import model.bean.Employees;
import model.bean.Privileges;
import model.dao.EmployeesDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.dao.PrivilegesDAO;
import utils.ManipularImagem;

/**
 *
 * @author Tong
 */
public class FEmployees extends javax.swing.JFrame {

    BufferedImage imagem;

    /**
     * Creates new form Employees
     */
    public FEmployees() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTEmployees.getModel();
        jTEmployees.setRowSorter(new TableRowSorter(modelo));

        readJTable();
        PrivilegesDAO prDAO = new PrivilegesDAO();
        EmployeesDAO pdao = new EmployeesDAO();
        for (Privileges pr : prDAO.list()) {
            jComboBox1.setSelectedItem(null);
            jComboBox1.addItem(pr);
        }
        for (Employees p : pdao.list()) {
            jComboBox2.setSelectedItem(null);
            jComboBox2.addItem(p);
        }
    }

    public void readJTable() {

        DefaultTableModel modelo = (DefaultTableModel) jTEmployees.getModel();
        modelo.setNumRows(0);
        EmployeesDAO pdao = new EmployeesDAO();
        PrivilegesDAO prDAO = new PrivilegesDAO();
        for (Employees p : pdao.list()) {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getName(),
                p.getEmail(),
                p.getCpf(),
                p.getCell_phone(),
                p.getFixed_phone(),
                p.getCep(),
                p.getAddress(),
                p.getAddress_number(),
                p.getComplement(),
                p.getCity(),
                p.getState(),
                p.getStatus(),
                p.getLogin(),
                p.getPassword(),
                p.getJob_title(),
                p.getReports_to(),
                p.getPrivilege(),
                p.getPhoto()

            });
        }
    }

    public void readJTableForName(String name) {
        DefaultTableModel modelo = (DefaultTableModel) jTEmployees.getModel();
        modelo.setNumRows(0);
        EmployeesDAO pdao = new EmployeesDAO();
        PrivilegesDAO prDAO = new PrivilegesDAO();

        for (Employees p : pdao.loadByName(name)) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getName(),
                p.getEmail(),
                p.getCpf(),
                p.getCell_phone(),
                p.getFixed_phone(),
                p.getCep(),
                p.getAddress(),
                p.getAddress_number(),
                p.getComplement(),
                p.getCity(),
                p.getState(),
                p.getStatus(),
                p.getLogin(),
                p.getPassword(),
                p.getJob_title(),
                p.getReports_to(),
                p.getPrivilege(),
                p.getPhoto()

            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCepEmployees = new javax.swing.JTextField();
        txtEstadoEmployees = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCidadeEmployees = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNumEnderecoEmployees = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEnderecoEmployees = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNomeEmployees = new javax.swing.JTextField();
        txtCelularEmployees = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCpfEmployees = new javax.swing.JTextField();
        txtTelefoFixoEmployees = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtComplementoEmployees = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTEmployees = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtEmailEmployees = new javax.swing.JTextField();
        txtTrabalhoEmployees = new javax.swing.JTextField();
        txtStatusEmployees = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtBuscaEmployees = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        txtIdEmployees = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtLoginEmployees = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtSenhaEmployees = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        imageSample = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("CIDADE");

        jLabel1.setText("ENDEREÇO");

        jLabel5.setText("NOME");

        jLabel8.setText("CELULAR");

        jLabel2.setText("CPF");

        jLabel6.setText("COMPLEMENTO");

        jLabel3.setText("CEP");

        jLabel7.setText("ESTADO");

        jLabel11.setText("TELEFONE FIXO");

        jLabel9.setText("NUMERO DE ENDEREÇO");

        jTEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "EMAIL", "CPF", "CELULAR", "TELEFONE FIXO", "CEP", "ENDEREÇO", "Nº ENDEREÇO", "COMPLEMENTO", "CIDADE", "ESTADO", "STATUS", "LOGIN", "SENHA", "FUNÇÃO", "REPORTA PARA (ID)", "ID PRIVILEGIO", "FOTO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Byte.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTEmployeesMouseClicked(evt);
            }
        });
        jTEmployees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTEmployeesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTEmployees);
        if (jTEmployees.getColumnModel().getColumnCount() > 0) {
            jTEmployees.getColumnModel().getColumn(13).setMinWidth(0);
            jTEmployees.getColumnModel().getColumn(13).setMaxWidth(0);
            jTEmployees.getColumnModel().getColumn(14).setMinWidth(0);
            jTEmployees.getColumnModel().getColumn(14).setMaxWidth(0);
            jTEmployees.getColumnModel().getColumn(15).setMinWidth(0);
            jTEmployees.getColumnModel().getColumn(15).setMaxWidth(0);
            jTEmployees.getColumnModel().getColumn(16).setMinWidth(0);
            jTEmployees.getColumnModel().getColumn(16).setMaxWidth(0);
            jTEmployees.getColumnModel().getColumn(17).setMinWidth(0);
            jTEmployees.getColumnModel().getColumn(17).setMaxWidth(0);
            jTEmployees.getColumnModel().getColumn(18).setMinWidth(0);
            jTEmployees.getColumnModel().getColumn(18).setMaxWidth(0);
        }

        jLabel10.setText("EMAIL");

        jLabel12.setText("STATUS");

        jLabel13.setText("FUNÇÃO");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Atualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtBuscaEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaEmployeesActionPerformed(evt);
            }
        });

        jButton4.setText("Busca");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtIdEmployees.setEnabled(false);

        jLabel14.setText("ID");

        jLabel15.setText("LOGIN");

        jLabel16.setText("SENHA");

        jLabel17.setText("REPORTA PARA (ID)");

        jLabel18.setText("ID PRIVILEGIO");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton5.setText("Carregar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        imageSample.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(txtIdEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNomeEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtCpfEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(txtEnderecoEmployees)
                                    .addComponent(txtCidadeEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtComplementoEmployees)
                                    .addComponent(txtEstadoEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9)
                                    .addComponent(txtCepEmployees)
                                    .addComponent(txtNumEnderecoEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(txtTelefoFixoEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtCelularEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEmailEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(imageSample, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17)
                            .addComponent(jComboBox1, 0, 204, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTrabalhoEmployees)
                            .addComponent(txtSenhaEmployees)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(txtStatusEmployees)
                            .addComponent(txtLoginEmployees))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(902, 902, 902)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(30, 30, 30)
                                        .addComponent(jButton2)
                                        .addGap(26, 26, 26)
                                        .addComponent(jButton3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtBuscaEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4))))
                            .addComponent(jScrollPane1))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscaEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIdEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtNomeEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCpfEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtEnderecoEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtComplementoEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txtEstadoEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtCepEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCidadeEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumEnderecoEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTelefoFixoEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCelularEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmailEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(26, 26, 26))
                            .addComponent(txtLoginEmployees, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStatusEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSenhaEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTrabalhoEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(28, 28, 28))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageSample, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//    public void readJTableForDesc(String desc) throws SQLException {
//
//        DefaultTableModel modelo = (DefaultTableModel) jTEmployees.getModel();
//        modelo.setNumRows(0);
//        EmployeesDAO pdao = new EmployeesDAO();
//
//        for (Employees p : pdao.readForDesc(desc)) {
//
//            modelo.addRow(new Object[]{
//                p.getId(),
//                p.getName(),
//                p.getEmail(),
//                p.getCpf(),
//                p.getCell_phone(),
//                p.getFixed_phone(),
//                p.getCep(),
//                p.getAddress(),
//                p.getAddress_number(),
//                p.getComplement(),
//                p.getCity(),
//                p.getState(),
//                p.getStatus(),
//                p.getLogin(),
//                p.getPassword(),
//                p.getJob_title(),
//                p.getReport_to(),
//                p.getPrivilegesId()
//            });
//
//        }
//
//    }
    private void jTEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTEmployeesMouseClicked
        if (jTEmployees.getSelectedRow() != -1) {

            txtIdEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 0).toString());
            txtNomeEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 1).toString());
            txtEmailEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 2).toString());
            txtCpfEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 3).toString());
            txtCelularEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 4).toString());
            txtTelefoFixoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 5).toString());
            txtCepEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 6).toString());
            txtEnderecoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 7).toString());
            txtNumEnderecoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 8).toString());
            txtComplementoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 9).toString());
            txtCidadeEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 10).toString());
            txtEstadoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 11).toString());
            txtStatusEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 12).toString());
            txtLoginEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 13).toString());
            txtSenhaEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 14).toString());
            txtTrabalhoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 15).toString());
            jComboBox1.setSelectedItem(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 17));
            jComboBox2.setSelectedItem(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 16));
            ManipularImagem.exibiImagemLabel((byte[]) jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 18), imageSample);

        }
    }//GEN-LAST:event_jTEmployeesMouseClicked

    private void jTEmployeesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTEmployeesKeyReleased
        if (jTEmployees.getSelectedRow() != -1) {

            txtIdEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 0).toString());
            txtNomeEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 1).toString());
            txtEmailEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 2).toString());
            txtCpfEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 3).toString());
            txtCelularEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 4).toString());
            txtTelefoFixoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 5).toString());
            txtCepEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 6).toString());
            txtEnderecoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 7).toString());
            txtNumEnderecoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 8).toString());
            txtComplementoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 9).toString());
            txtCidadeEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 10).toString());
            txtEstadoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 11).toString());
            txtStatusEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 12).toString());
            txtLoginEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 13).toString());
            txtSenhaEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 14).toString());
            txtTrabalhoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 15).toString());
            jComboBox1.setSelectedItem(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 17));
            jComboBox2.setSelectedItem(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 16));
            ManipularImagem.exibiImagemLabel((byte[]) jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 18), imageSample);
        }
    }//GEN-LAST:event_jTEmployeesKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Employees p = new Employees();
        EmployeesDAO dao = new EmployeesDAO();
        Privileges privileges = (Privileges) jComboBox1.getSelectedItem();
        Employees employees = (Employees) jComboBox2.getSelectedItem();
        p.setName(txtNomeEmployees.getText());
        p.setCpf(txtCpfEmployees.getText());
        p.setAddress_number(Integer.parseInt(txtNumEnderecoEmployees.getText()));
        p.setAddress(txtEnderecoEmployees.getText());
        p.setComplement(txtComplementoEmployees.getText());
        p.setState(txtEstadoEmployees.getText());
        p.setCity(txtCidadeEmployees.getText());
        p.setCep(txtCepEmployees.getText());
        p.setFixed_phone(txtTelefoFixoEmployees.getText());
        p.setCell_phone(txtCelularEmployees.getText());
        p.setEmail(txtEmailEmployees.getText());
        p.setStatus(txtStatusEmployees.getText());
        p.setLogin(txtLoginEmployees.getText());
        p.setPassword(txtSenhaEmployees.getText());
        p.setJob_title(txtTrabalhoEmployees.getText());
        p.setPhoto(ManipularImagem.getImgBytes(imagem));
        if (employees != null) {
            p.setReports_to(employees);
        } else {
            p.setReports_to(null);
        }
        p.setPrivilege(privileges);
        dao.create(p);
        txtIdEmployees.setText("");
        txtNomeEmployees.setText("");
        txtEmailEmployees.setText("");
        txtCpfEmployees.setText("");
        txtCelularEmployees.setText("");
        txtTelefoFixoEmployees.setText("");
        txtCepEmployees.setText("");
        txtEnderecoEmployees.setText("");
        txtNumEnderecoEmployees.setText("");
        txtComplementoEmployees.setText("");
        txtCidadeEmployees.setText("");
        txtEstadoEmployees.setText("");
        txtStatusEmployees.setText("");
        txtLoginEmployees.setText("");
        txtSenhaEmployees.setText("");
        txtTrabalhoEmployees.setText("");
        imageSample.setIcon(null);
        readJTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTEmployees.getSelectedRow() != -1) {

            Employees p = new Employees();
            EmployeesDAO dao = new EmployeesDAO();
            p.setId((int) jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 0));
            dao.delete(p);
            txtIdEmployees.setText("");
            txtNomeEmployees.setText("");
            txtEmailEmployees.setText("");
            txtCpfEmployees.setText("");
            txtCelularEmployees.setText("");
            txtTelefoFixoEmployees.setText("");
            txtCepEmployees.setText("");
            txtEnderecoEmployees.setText("");
            txtNumEnderecoEmployees.setText("");
            txtComplementoEmployees.setText("");
            txtCidadeEmployees.setText("");
            txtEstadoEmployees.setText("");
            txtStatusEmployees.setText("");
            txtLoginEmployees.setText("");
            txtSenhaEmployees.setText("");
            txtTrabalhoEmployees.setText("");
            imageSample.setIcon(null);
            readJTable();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um empregado para excluir.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jTEmployees.getSelectedRow() != -1) {
            Employees p = new Employees();
            EmployeesDAO dao = new EmployeesDAO();
            Privileges privileges = (Privileges) jComboBox1.getSelectedItem();
            Employees employees = (Employees) jComboBox2.getSelectedItem();
            p.setName(txtNomeEmployees.getText());
            p.setCpf(txtCpfEmployees.getText());
            p.setAddress_number(Integer.parseInt(txtNumEnderecoEmployees.getText()));
            p.setAddress(txtEnderecoEmployees.getText());
            p.setComplement(txtComplementoEmployees.getText());
            p.setState(txtEstadoEmployees.getText());
            p.setCity(txtCidadeEmployees.getText());
            p.setCep(txtCepEmployees.getText());
            p.setFixed_phone(txtTelefoFixoEmployees.getText());
            p.setCell_phone(txtCelularEmployees.getText());
            p.setEmail(txtEmailEmployees.getText());
            p.setStatus(txtStatusEmployees.getText());
            p.setLogin(txtLoginEmployees.getText());
            p.setPassword(txtSenhaEmployees.getText());
            p.setJob_title(txtTrabalhoEmployees.getText());
            p.setPhoto(ManipularImagem.getImgBytes(imagem));
            if (employees != null) {
                p.setReports_to(employees);
            } else {
                p.setReports_to(null);
            }
            p.setPrivilege(privileges);
            p.setId((int) jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 0));
            try {
                dao.alter(p);
            } catch (Exception ex) {
                Logger.getLogger(FEmployees.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtIdEmployees.setText("");
            txtNomeEmployees.setText("");
            txtEmailEmployees.setText("");
            txtCpfEmployees.setText("");
            txtCelularEmployees.setText("");
            txtTelefoFixoEmployees.setText("");
            txtCepEmployees.setText("");
            txtEnderecoEmployees.setText("");
            txtNumEnderecoEmployees.setText("");
            txtComplementoEmployees.setText("");
            txtCidadeEmployees.setText("");
            txtEstadoEmployees.setText("");
            txtStatusEmployees.setText("");
            txtLoginEmployees.setText("");
            txtSenhaEmployees.setText("");
            txtTrabalhoEmployees.setText("");
            imageSample.setIcon(null);
            readJTable();

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtBuscaEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaEmployeesActionPerformed
        jButton4.setEnabled(true);
    }//GEN-LAST:event_txtBuscaEmployeesActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        readJTableForName(txtBuscaEmployees.getText());

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JFileChooser fc = new JFileChooser();
        int res = fc.showOpenDialog(null);

        if (res == JFileChooser.APPROVE_OPTION) {
            File arquivo = fc.getSelectedFile();

            try {
                imagem = ManipularImagem.setImagemDimensao(arquivo.getAbsolutePath(), 160, 160);

                imageSample.setIcon(new ImageIcon(imagem));

            } catch (Exception ex) {
                // System.out.println(ex.printStackTrace().toString());
            }

        } else {
            JOptionPane.showMessageDialog(null, "Voce nao selecionou nenhum arquivo.");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FEmployees().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(FEmployees.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageSample;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<Object> jComboBox1;
    private javax.swing.JComboBox<Object> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTEmployees;
    private javax.swing.JTextField txtBuscaEmployees;
    private javax.swing.JTextField txtCelularEmployees;
    private javax.swing.JTextField txtCepEmployees;
    private javax.swing.JTextField txtCidadeEmployees;
    private javax.swing.JTextField txtComplementoEmployees;
    private javax.swing.JTextField txtCpfEmployees;
    private javax.swing.JTextField txtEmailEmployees;
    private javax.swing.JTextField txtEnderecoEmployees;
    private javax.swing.JTextField txtEstadoEmployees;
    private javax.swing.JTextField txtIdEmployees;
    private javax.swing.JTextField txtLoginEmployees;
    private javax.swing.JTextField txtNomeEmployees;
    private javax.swing.JTextField txtNumEnderecoEmployees;
    private javax.swing.JTextField txtSenhaEmployees;
    private javax.swing.JTextField txtStatusEmployees;
    private javax.swing.JTextField txtTelefoFixoEmployees;
    private javax.swing.JTextField txtTrabalhoEmployees;
    // End of variables declaration//GEN-END:variables
}
