/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import model.dao.OrdersDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;
import model.bean.Orders;

/**
 *
 * @author Tong
 */
public class Forders extends javax.swing.JFrame {

    /**
     * Creates new form Orders
     */
    public Forders() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTOrders.getModel();
        jTOrders.setRowSorter(new TableRowSorter(modelo));

        readJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdOrders = new javax.swing.JTextField();
        txtDescontoOrders = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDataOrders = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtSituacaoOrders = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtObservacoesOrders = new javax.swing.JTextField();
        txtPrecoTotalOrders = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTOrders = new javax.swing.JTable();
        txtBuscaOrders = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtIdEmpregadoOrders = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtIdBudgetOrders = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        budgetClient = new javax.swing.JTextField();
        budgetVehicle = new javax.swing.JTextField();
        budgetService = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("DATA");

        jLabel1.setText("SITUAÇÃO");

        jLabel5.setText("PREÇO TOTAL (R$)");

        jLabel9.setText("ID");

        jLabel11.setText("OBSERVAÇÕES");

        jLabel2.setText("DESCONTO (R$)");

        jTOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DESCONTO", "OBSERVAÇÕES", "PREÇO TOTAL", "SITUAÇÃO", "DATA", "FUNCIONÁRIO", "DATA DO ORÇAMENTO", "CLIENTE", "VEICULO", "SERVIÇO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTOrdersMouseClicked(evt);
            }
        });
        jTOrders.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTOrdersKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTOrders);

        txtBuscaOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaOrdersActionPerformed(evt);
            }
        });

        jButton4.setText("Busca");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Atualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setText("FUNCIONÁRIO");

        jLabel12.setText("DATA DO ORÇAMENTO");

        jLabel3.setText("CLIENTE");

        jLabel6.setText("VEICULO");

        jLabel7.setText("SERVIÇO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPrecoTotalOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addComponent(jLabel2))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(txtDescontoOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(txtSituacaoOrders)))
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtObservacoesOrders, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(30, 30, 30)
                                    .addComponent(jButton2)
                                    .addGap(26, 26, 26)
                                    .addComponent(jButton3))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtIdEmpregadoOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(txtDataOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(120, 120, 120)
                                .addComponent(jLabel10)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtIdBudgetOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(budgetClient, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(budgetVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(budgetService)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtBuscaOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscaOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDataOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdEmpregadoOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdBudgetOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(budgetClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(budgetVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(budgetService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrecoTotalOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescontoOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSituacaoOrders))))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtObservacoesOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void readJTable() {

        DefaultTableModel modelo = (DefaultTableModel) jTOrders.getModel();
        modelo.setNumRows(0);
        OrdersDAO pdao = new OrdersDAO();

        for (Orders p : pdao.list()) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getDiscount(),
                p.getObservation() == null ? "-" : p.getObservation(),
                p.getPayment(),
                p.getSituation(),
                p.getDate(),
                p.getEmployees().getName(),
                p.getBudget().getDate(),
                p.getBudget().getClient().getName(),
                p.getBudget().getVehicle().getPlate(),
                p.getBudget().getService().getName()
            });

        }

    }

    public void readJTableForDesc(int id) throws SQLException {

        DefaultTableModel modelo = (DefaultTableModel) jTOrders.getModel();
        modelo.setNumRows(0);
        OrdersDAO pdao = new OrdersDAO();

        for (Orders p : pdao.loadById(id)) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getDiscount(),
                p.getObservation() == null ? "-" : p.getObservation(),
                p.getPayment(),
                p.getSituation(),
                p.getDate(),
                p.getEmployees().getName(),
                p.getBudget().getDate(),
                p.getBudget().getClient().getName(),
                p.getBudget().getVehicle().getPlate(),
                p.getBudget().getService().getName()
            });

        }
    }

    private void jTOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTOrdersMouseClicked
        if (jTOrders.getSelectedRow() != -1) {

            txtIdOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 0).toString());
            txtDescontoOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 1).toString());
            txtObservacoesOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 2).toString());
            txtPrecoTotalOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 3).toString());
            txtSituacaoOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 4).toString());
            txtDataOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 5).toString());
            txtIdEmpregadoOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 6).toString());
            txtIdBudgetOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 7).toString());
            budgetClient.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 8).toString());
            budgetVehicle.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 9).toString());
            budgetService.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 10).toString());

        }
    }//GEN-LAST:event_jTOrdersMouseClicked

    private void jTOrdersKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTOrdersKeyReleased
        if (jTOrders.getSelectedRow() != -1) {
            txtIdOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 0).toString());
            txtDescontoOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 1).toString());
            txtObservacoesOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 2).toString());
            txtPrecoTotalOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 3).toString());
            txtSituacaoOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 4).toString());
            txtDataOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 5).toString());
            txtIdEmpregadoOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 6).toString());
            txtIdBudgetOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 7).toString());
            budgetClient.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 8).toString());
            budgetVehicle.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 9).toString());
            budgetService.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 10).toString());
        }
    }//GEN-LAST:event_jTOrdersKeyReleased

    private void txtBuscaOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaOrdersActionPerformed
        jButton4.setEnabled(true);
    }//GEN-LAST:event_txtBuscaOrdersActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

//        readJTableForDesc(txtBuscaOrders.getText());

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Orders p = new Orders();
        OrdersDAO dao = new OrdersDAO();
        p.setId(Integer.parseInt(txtIdOrders.getText()));
        p.setDiscount(Double.parseDouble(txtDescontoOrders.getText()));
        p.setObservation(txtObservacoesOrders.getText());
        p.setPayment(txtPrecoTotalOrders.getText());
        p.setSituation(txtDataOrders.getText());
//        p.setEmployees(Integer.parseInt(txtIdEmpregadoOrders.getText()));
//        p.setBudget(Integer.parseInt(txtIdBudgetOrders.getText()));
        dao.create(p);
        txtIdOrders.setText("");
        txtDescontoOrders.setText("");
        txtObservacoesOrders.setText("");
        txtPrecoTotalOrders.setText("");
        txtSituacaoOrders.setText("");
        txtDataOrders.setText("");
        txtIdEmpregadoOrders.setText("");
        txtIdBudgetOrders.setText("");
        readJTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTOrders.getSelectedRow() != -1) {

            Orders p = new Orders();
            OrdersDAO dao = new OrdersDAO();
            p.setId((int) jTOrders.getValueAt(jTOrders.getSelectedRow(), 0));
            dao.delete(p);
            txtIdOrders.setText("");
            txtDescontoOrders.setText("");
            txtObservacoesOrders.setText("");
            txtPrecoTotalOrders.setText("");
            txtSituacaoOrders.setText("");
            txtDataOrders.setText("");
            txtIdEmpregadoOrders.setText("");
            txtIdBudgetOrders.setText("");
            readJTable();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma ordem para excluir.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jTOrders.getSelectedRow() != -1) {

            Orders p = new Orders();
            OrdersDAO dao = new OrdersDAO();
            p.setId(Integer.parseInt(txtIdOrders.getText()));
            p.setDiscount(Double.parseDouble(txtDescontoOrders.getText()));
            p.setObservation(txtObservacoesOrders.getText());
            p.setPayment(txtPrecoTotalOrders.getText());
            p.setSituation(txtDataOrders.getText());
//        p.setEmployees(Integer.parseInt(txtIdEmpregadoOrders.getText()));
//        p.setBudget(Integer.parseInt(txtIdBudgetOrders.getText()));
            p.setId((int) jTOrders.getValueAt(jTOrders.getSelectedRow(), 0));
            try {
                dao.alter(p);
            } catch (Exception ex) {
                Logger.getLogger(Forders.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtIdOrders.setText("");
            txtDescontoOrders.setText("");
            txtObservacoesOrders.setText("");
            txtPrecoTotalOrders.setText("");
            txtSituacaoOrders.setText("");
            txtDataOrders.setText("");
            txtIdEmpregadoOrders.setText("");
            txtIdBudgetOrders.setText("");
            readJTable();

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField budgetClient;
    private javax.swing.JTextField budgetService;
    private javax.swing.JTextField budgetVehicle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTOrders;
    private javax.swing.JTextField txtBuscaOrders;
    private javax.swing.JTextField txtDataOrders;
    private javax.swing.JTextField txtDescontoOrders;
    private javax.swing.JTextField txtIdBudgetOrders;
    private javax.swing.JTextField txtIdEmpregadoOrders;
    private javax.swing.JTextField txtIdOrders;
    private javax.swing.JTextField txtObservacoesOrders;
    private javax.swing.JTextField txtPrecoTotalOrders;
    private javax.swing.JTextField txtSituacaoOrders;
    // End of variables declaration//GEN-END:variables
}
