/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import model.dao.OrdensDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.bean.Ordens;
/**
 *
 * @author Tong
 */
public class FOrdens extends javax.swing.JFrame {

    /**
     * Creates new form Ordens
     */
    public FOrdens() {
        initComponents();
        
        jButton4.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdOrdens = new javax.swing.JTextField();
        txtTotalItensOrdens = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrecoServicoOrdens = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtSituacaoOrdens = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtObservacoesOrdens = new javax.swing.JTextField();
        txtPrecoTotalOrdens = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTOrdens = new javax.swing.JTable();
        txtBuscaOrdens = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("PREÇO DO SERVIÇO");

        jLabel1.setText("SITUAÇÃO");

        jLabel5.setText("PREÇO TOTAL");

        jLabel9.setText("ID");

        jLabel11.setText("OBSERVAÇÕES");

        jLabel2.setText("TOTAL DE ITENS");

        jTOrdens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TOTAL", "TOTAL DE ITENS", "OBSERVAÇÕES", "PREÇO DO SERVIÇO", "SITUAÇÃO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTOrdens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTOrdensMouseClicked(evt);
            }
        });
        jTOrdens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTOrdensKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTOrdens);

        txtBuscaOrdens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaOrdensActionPerformed(evt);
            }
        });

        jButton4.setText("Busca");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Atualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(30, 30, 30)
                                .addComponent(jButton2)
                                .addGap(26, 26, 26)
                                .addComponent(jButton3)
                                .addGap(56, 56, 56)
                                .addComponent(txtBuscaOrdens, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(txtPrecoTotalOrdens, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTotalItensOrdens, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(txtSituacaoOrdens, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(txtPrecoServicoOrdens, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(txtObservacoesOrdens, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(txtIdOrdens, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(170, 170, 170)
                                .addComponent(jLabel2)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtIdOrdens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPrecoTotalOrdens, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTotalItensOrdens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSituacaoOrdens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecoServicoOrdens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtObservacoesOrdens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton3)
                        .addComponent(jButton2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscaOrdens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void readJTable() throws SQLException {
        
        DefaultTableModel modelo = (DefaultTableModel) jTOrdens.getModel();
        modelo.setNumRows(0);
        OrdensDAO pdao = new OrdensDAO();

        for (Ordens p : pdao.read()) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getTotal(),
                p.getTotal_itens(),
                p.getObservation(),
                p.getPrice_services(),
                p.getSituation()
            });

        }

    }
    
    
    public void readJTableForDesc(String desc) throws SQLException {
        
        DefaultTableModel modelo = (DefaultTableModel) jTOrdens.getModel();
        modelo.setNumRows(0);
        OrdensDAO pdao = new OrdensDAO();

        for (Ordens p : pdao.readForDesc(desc)) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getTotal(),
                p.getTotal_itens(),
                p.getObservation(),
                p.getPrice_services(),
                p.getSituation()
            });

        }
    }
    
    private void jTOrdensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTOrdensMouseClicked
        if (jTOrdens.getSelectedRow() != -1) {

            txtIdOrdens.setText(jTOrdens.getValueAt(jTOrdens.getSelectedRow(), 1).toString());
            txtPrecoTotalOrdens.setText(jTOrdens.getValueAt(jTOrdens.getSelectedRow(), 2).toString());
            txtTotalItensOrdens.setText(jTOrdens.getValueAt(jTOrdens.getSelectedRow(), 3).toString());
            txtObservacoesOrdens.setText(jTOrdens.getValueAt(jTOrdens.getSelectedRow(), 4).toString());
            txtPrecoServicoOrdens.setText(jTOrdens.getValueAt(jTOrdens.getSelectedRow(), 5).toString());
            txtSituacaoOrdens.setText(jTOrdens.getValueAt(jTOrdens.getSelectedRow(), 6).toString());
            
        }
    }//GEN-LAST:event_jTOrdensMouseClicked

    private void jTOrdensKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTOrdensKeyReleased
        if (jTOrdens.getSelectedRow() != -1) {

            txtIdOrdens.setText(jTOrdens.getValueAt(jTOrdens.getSelectedRow(), 1).toString());
            txtPrecoTotalOrdens.setText(jTOrdens.getValueAt(jTOrdens.getSelectedRow(), 2).toString());
            txtTotalItensOrdens.setText(jTOrdens.getValueAt(jTOrdens.getSelectedRow(), 3).toString());
            txtObservacoesOrdens.setText(jTOrdens.getValueAt(jTOrdens.getSelectedRow(), 4).toString());
            txtPrecoServicoOrdens.setText(jTOrdens.getValueAt(jTOrdens.getSelectedRow(), 5).toString());
            txtSituacaoOrdens.setText(jTOrdens.getValueAt(jTOrdens.getSelectedRow(), 6).toString());
        }
    }//GEN-LAST:event_jTOrdensKeyReleased

    private void txtBuscaOrdensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaOrdensActionPerformed
        jButton4.setEnabled(true);
    }//GEN-LAST:event_txtBuscaOrdensActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            readJTableForDesc(txtBuscaOrdens.getText());
        } catch (SQLException ex) {
            Logger.getLogger(FOrdens.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Ordens p = new Ordens();
            OrdensDAO dao = new OrdensDAO();

            p.setId(Integer.parseInt(txtIdOrdens.getText()));
            p.setTotal(Double.parseDouble(txtPrecoTotalOrdens.getText()));
            p.setTotal_itens(Integer.parseInt(txtTotalItensOrdens.getText()));
            p.setObservation(txtObservacoesOrdens.getText());
            p.setPrice_services(Double.parseDouble(txtPrecoServicoOrdens.getText()));
            p.setSituation(txtSituacaoOrdens.getText());
            dao.create(p);

            txtIdOrdens.setText("");
            txtPrecoTotalOrdens.setText("");
            txtTotalItensOrdens.setText("");
            txtObservacoesOrdens.setText("");
            txtPrecoServicoOrdens.setText("");
            txtSituacaoOrdens.setText("");

            readJTable();

        } catch (SQLException ex) {
            Logger.getLogger(FOrdens.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTOrdens.getSelectedRow() != -1) {

            try {

                Ordens p = new Ordens();
                OrdensDAO dao = new OrdensDAO();

                p.setId((int) jTOrdens.getValueAt(jTOrdens.getSelectedRow(), 0));

                dao.delete(p);

                txtIdOrdens.setText("");
                txtPrecoTotalOrdens.setText("");
                txtTotalItensOrdens.setText("");
                txtObservacoesOrdens.setText("");
                txtPrecoServicoOrdens.setText("");
                txtSituacaoOrdens.setText("");

                readJTable();

            } catch (SQLException ex) {
                Logger.getLogger(FOrdens.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma ordem para excluir.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jTOrdens.getSelectedRow() != -1) {

            try {

                Ordens p = new Ordens();
                OrdensDAO dao = new OrdensDAO();
                
                p.setId(Integer.parseInt(txtIdOrdens.getText()));
                p.setTotal(Double.parseDouble(txtPrecoTotalOrdens.getText()));
                p.setTotal_itens(Integer.parseInt(txtTotalItensOrdens.getText()));
                p.setObservation(txtObservacoesOrdens.getText());
                p.setPrice_services(Double.parseDouble(txtPrecoServicoOrdens.getText()));
                p.setSituation(txtSituacaoOrdens.getText());
                p.setId((int) jTOrdens.getValueAt(jTOrdens.getSelectedRow(), 0));

                try {
                    dao.update(p);
                } catch (SQLException ex) {
                    Logger.getLogger(FOrdens.class.getName()).log(Level.SEVERE, null, ex);
                }

                txtIdOrdens.setText("");
                txtPrecoTotalOrdens.setText("");
                txtTotalItensOrdens.setText("");
                txtObservacoesOrdens.setText("");
                txtPrecoServicoOrdens.setText("");
                txtSituacaoOrdens.setText("");
                readJTable();

            } catch (SQLException ex) {
                Logger.getLogger(FOrdens.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FOrdens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FOrdens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FOrdens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FOrdens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FOrdens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTOrdens;
    private javax.swing.JTextField txtBuscaOrdens;
    private javax.swing.JTextField txtIdOrdens;
    private javax.swing.JTextField txtObservacoesOrdens;
    private javax.swing.JTextField txtPrecoServicoOrdens;
    private javax.swing.JTextField txtPrecoTotalOrdens;
    private javax.swing.JTextField txtSituacaoOrdens;
    private javax.swing.JTextField txtTotalItensOrdens;
    // End of variables declaration//GEN-END:variables
}
