-- MySQL Script generated by MySQL Workbench
-- Wed Oct 27 03:14:20 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(14) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `address_number` VARCHAR(45) NOT NULL,
  `complement` VARCHAR(255) NOT NULL,
  `state` CHAR(2) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `cell_phone` VARCHAR(15) NOT NULL,
  `fixed_phone` VARCHAR(14) NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`privileges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`privileges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `is_superadmin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `photo` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `cell_phone` VARCHAR(15) NOT NULL,
  `fixed_phone` VARCHAR(14) NULL,
  `cep` VARCHAR(10) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `address_number` VARCHAR(45) NOT NULL,
  `complement` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `state` CHAR(2) NOT NULL,
  `status` TINYINT NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `job_title` VARCHAR(255) NULL,
  `reports_to` INT NULL,
  `privileges_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employees_employees1_idx` (`reports_to` ASC),
  INDEX `fk_employees_privileges1_idx` (`privileges_id` ASC),
  CONSTRAINT `fk_employees_employees1`
    FOREIGN KEY (`reports_to`)
    REFERENCES `mydb`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_privileges1`
    FOREIGN KEY (`privileges_id`)
    REFERENCES `mydb`.`privileges` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vehicles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `plate` VARCHAR(45) NOT NULL,
  `year` YEAR(4) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `type_fuel` VARCHAR(45) NULL,
  `km_current` DOUBLE NULL DEFAULT NULL,
  `clients_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vehicles_customers_idx` (`clients_id` ASC),
  CONSTRAINT `fk_vehicles_customers`
    FOREIGN KEY (`clients_id`)
    REFERENCES `mydb`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`providers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(18) NOT NULL,
  `cell_phone` VARCHAR(15) NOT NULL,
  `fixed_phone` VARCHAR(14) NULL,
  `cep` VARCHAR(10) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `address_number` VARCHAR(45) NOT NULL,
  `complement` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `state` CHAR(2) NOT NULL,
  `url_site` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `category` VARCHAR(45) NULL,
  `price` DECIMAL(10,2) NULL,
  `barcode` INT NULL,
  `photo` VARCHAR(255) NULL,
  `providers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_providers1_idx` (`providers_id` ASC),
  CONSTRAINT `fk_products_providers1`
    FOREIGN KEY (`providers_id`)
    REFERENCES `mydb`.`providers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`budget`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`budget` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price_services` DECIMAL(10,2) NULL,
  `total_items` DECIMAL(10,2) NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `date` DATE NOT NULL,
  `vehicles_id` INT NOT NULL,
  `services_id` INT NOT NULL,
  `clients_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_budget_clients1_idx` (`clients_id` ASC),
  INDEX `fk_budget_vehicles1_idx` (`vehicles_id` ASC),
  INDEX `fk_budget_services1_idx` (`services_id` ASC),
  CONSTRAINT `fk_budget_clients1`
    FOREIGN KEY (`clients_id`)
    REFERENCES `mydb`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_budget_vehicles1`
    FOREIGN KEY (`vehicles_id`)
    REFERENCES `mydb`.`vehicles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_budget_services1`
    FOREIGN KEY (`services_id`)
    REFERENCES `mydb`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `discount` DECIMAL(10,2) NULL,
  `observation` VARCHAR(45) NULL,
  `payment` VARCHAR(191) NULL DEFAULT NULL,
  `situation` VARCHAR(191) NOT NULL DEFAULT 'Aberto',
  `date` DATE NOT NULL,
  `employees_id` INT NOT NULL,
  `budget_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_employees1_idx` (`employees_id` ASC),
  INDEX `fk_orders_budget1_idx` (`budget_id` ASC),
  CONSTRAINT `fk_orders_employees1`
    FOREIGN KEY (`employees_id`)
    REFERENCES `mydb`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_budget1`
    FOREIGN KEY (`budget_id`)
    REFERENCES `mydb`.`budget` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`budget_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`budget_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL(10,2) NOT NULL,
  `amount` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `subtotal` DECIMAL(10,2) NOT NULL,
  `budget_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_budget_details_budget1_idx` (`budget_id` ASC),
  INDEX `fk_budget_details_products1_idx` (`products_id` ASC),
  CONSTRAINT `fk_budget_details_budget1`
    FOREIGN KEY (`budget_id`)
    REFERENCES `mydb`.`budget` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_budget_details_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `mydb`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
